name: Build React
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: BuildTools
        run: |
          touch test
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: educator
          key: ${{ secrets.SERVER_KEY }}
          source: 'test'
          target: '/home/educator/Dockerize/deployment'
          args: '-r -P 1313'
