name: Build React
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: BuildTools
        run: |
          touch test
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: educator
          key: ${{ secrets.SERVER_KEY }}
          source: 'test'
          target: '/home/educator/Dockerize/deployment'
          args: '-P 1313'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: educator
          port: 1313
          key: ${{ secrets.SERVER_KEY }}
          script: |
            chgrp -R Educator /home/educator/Dockerize/deployment/test
            bash -ic 'adopse restart'

            
